# Generated by Django 4.1.3 on 2022-12-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_ID', models.IntegerField(max_length=4)),
                ('Full_Name', models.CharField(max_length=256)),
                ('Phone_Number', models.CharField(max_length=256)),
                ('Email_Address', models.EmailField(max_length=254)),
                ('Profile_Image', models.ImageField(default='default.jpg', upload_to='')),
                ('Password', models.CharField(max_length=256)),
                ('Roles', models.IntegerField()),
            ],
        ),
    ]
