# Generated by Django 4.1.3 on 2022-12-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_roles_alter_employee_roles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='Roles_ID',
            new_name='Role_ID',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='Roles_Name',
            new_name='Role_Name',
        ),
    ]
