# Generated by Django 4.1.3 on 2022-12-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_rename_roles_role_rename_roles_id_role_role_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Roles',
            new_name='Role',
        ),
    ]
