# Generated by Django 4.1.3 on 2022-12-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_rename_roles_employee_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='Employee_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
