# Generated by Django 4.1.3 on 2022-12-13 03:47

from django.db import migrations, models
import django.db.models.deletion
import index.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Full_Name', models.CharField(max_length=100)),
                ('Phone_Number', models.CharField(max_length=100)),
                ('Email_Address', models.EmailField(max_length=254)),
                ('Profile_Image', models.ImageField(blank=True, null=True, upload_to=index.models.user_directory_path)),
                ('Password', models.CharField(max_length=256)),
                ('Start_Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('Role_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Role_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('WorkSchedule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateNow', models.DateField()),
                ('Present', models.BooleanField()),
                ('InTime', models.DateTimeField()),
                ('OutTime', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('Employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.role'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('Attendance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateNow', models.DateField(null=True)),
                ('Present', models.BooleanField(null=True)),
                ('InTime', models.DateTimeField(blank=True, null=True)),
                ('OutTime', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('Employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.employee')),
            ],
        ),
    ]
