# Generated by Django 4.1.3 on 2022-12-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Profile_Image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
