# Generated by Django 4.1.3 on 2022-12-09 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_employee_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roles_ID', models.IntegerField()),
                ('Roles_Name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='Roles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.roles'),
        ),
    ]
